[general]
import = [
  "~/.config/alacritty/catppuccin-latte.toml"
]

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 11.5

[terminal.shell]
program = "/usr/bin/tmux"
args = ["new-session"]

[window]
padding = { x = 8, y = 6 }
opacity = 0.95

[cursor]
style = { shape = "Beam", blinking = "Always" }